[build-system]
build-backend = "hatchling.build"
requires = [
    "hatchling",
]

[project]
name = "aa-fatanalysis"
description = "FAT Analysis Plugin for Alliance Auth"
readme = "README.md"
keywords = [
    "allianceauth",
    "fatanalysis",
]
license = { file = "LICENSE" }
authors = [
    { name = "Maddog Broekman", email = "maddogbroekman@gmail.com" },
]
requires-python = ">=3.10,<3.14"
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dynamic = [
    "version",
]
dependencies = [
    "allianceauth>=5",
]

[tool.hatch]
version.path = "fatanalysis/__init__.py"
build.include = [
    "/fatanalysis",
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
version_files = [ "fatanalysis/__init__.py", "pyproject.toml:version" ]
tag_format = "v$version"
update_changelog_on_bump = true
