# Generated by Django 5.2.16 on 2026-07-31 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.CharField(max_length=255)),
                ('period_type', models.IntegerField(choices=[(30, '30 Days'), (90, '90 Days')])),
            ],
        ),
        migrations.CreateModel(
            name='FatEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=255)),
                ('total_fats', models.IntegerField(default=0)),
                ('fat_details', models.JSONField(blank=True, default=dict)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.evecharacter')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fat_entries', to='fatanalysis.uploadperiod')),
            ],
        ),
    ]
