# Generated by Django 5.2.15 on 2026-07-31 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fatanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadperiod',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
